version: "3.3"
services:
  app:
    image: node
    container_name: mailer
    working_dir: /app
    command: bash -c "yarn && yarn dev"
    ports:
      - "3005:3005"
    volumes:
      - .:/app
  redis:
    image: "redis:latest"
    container_name: redis
    restart: always
    ports:
      - "6379"
